image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Terraform dependencies
    init: |
      sudo apt-get update
      sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    command: |
      sudo apt-get update
      sudo apt-get install terraform
      echo "You are on" `terraform version`
      gp sync-done build

  - name: Initalise terraform
    init: gp sync-await build
    command: |
      export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
      export AWS_SECRET_ACCESS_KEY="$AWS_SECRETS_ACCESS_KEY"
      export AWS_DEFAULT_REGION="eu-west-1"
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform
