# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: AWS Set-up
    init: aws configure
  - name: Install Terraform depdencies
    init: |
      sudo apt-get update
      sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    command: |
      sudo apt-get update
      sudo apt-get install terraform
      echo "You are on" `terraform version`
      gp sync-done build
    openMode: split-left
  - name: Inialise terraform
    init: gp sync-await build
    command: terraform init && terraform apply
    openMode: split-right

ports:
  - port: 8000
    onOpen: open-preview
    visibility: private
